# Generated by Django 5.0.6 on 2024-06-22 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoVehiculo',
            fields=[
                ('id_tipo_vehiculo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('numero_ruedas', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('placa', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('modelo', models.CharField(blank=True, max_length=25, null=True)),
                ('marca', models.CharField(blank=True, max_length=25, null=True)),
                ('color', models.CharField(blank=True, max_length=25, null=True)),
                ('transmision', models.CharField(blank=True, max_length=30, null=True)),
                ('documento', models.ForeignKey(db_column='Documento', on_delete=django.db.models.deletion.CASCADE, to='Clientes.clientes')),
                ('id_tipo_vehiculo', models.ForeignKey(db_column='id_tipo_vehiculo', on_delete=django.db.models.deletion.CASCADE, to='Vehiculo.tipovehiculo')),
            ],
        ),
    ]
