# Generated by Django 5.0.6 on 2024-06-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('placa', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('modelo', models.CharField(blank=True, max_length=25, null=True)),
                ('marca', models.CharField(blank=True, max_length=25, null=True)),
                ('color', models.CharField(blank=True, max_length=25, null=True)),
                ('transmision', models.CharField(blank=True, max_length=30, null=True)),
                ('documento', models.CharField(blank=True, max_length=10, null=True)),
                ('id_tipo_vehiculo', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
    ]
