# Generated by Django 5.0.6 on 2024-06-12 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0002_clientes_delete_cliente'),
        ('Vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='documento',
            field=models.ForeignKey(db_column='documento', on_delete=django.db.models.deletion.CASCADE, to='Clientes.clientes'),
        ),
    ]
