# Generated by Django 5.0.6 on 2024-06-12 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0002_clientes_delete_cliente'),
        ('Vehiculo', '0002_alter_vehiculo_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoVehiculo',
            fields=[
                ('id_tipo_vehiculo', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('numero_ruedas', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='documento',
            field=models.ForeignKey(db_column='Documento', on_delete=django.db.models.deletion.CASCADE, to='Clientes.clientes'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='id_tipo_vehiculo',
            field=models.ForeignKey(db_column='id_tipo_vehiculo', on_delete=django.db.models.deletion.CASCADE, to='Vehiculo.tipovehiculo'),
        ),
    ]
