# Generated by Django 5.0.6 on 2024-06-15 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehiculo', '0003_tipovehiculo_alter_vehiculo_documento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipovehiculo',
            name='id_tipo_vehiculo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
