# Generated by Django 5.0.6 on 2024-06-22 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id_servicios', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('descripcion', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
