# Generated by Django 5.0.6 on 2024-06-12 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id_servicios', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('nombre_servicio', models.CharField(blank=True, max_length=50, null=True)),
                ('precio', models.FloatField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
