# Generated by Django 5.0.6 on 2024-06-12 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicios',
            name='descripcion',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
