# Generated by Django 5.0.6 on 2024-06-15 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0002_alter_servicios_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicios',
            name='id_servicios',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
