# Generated by Django 5.0.6 on 2024-06-20 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0003_alter_servicios_id_servicios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicios',
            old_name='nombre_servicio',
            new_name='nombre',
        ),
    ]
