# Generated by Django 5.0.6 on 2024-06-15 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Productos', '0003_alter_tipoproducto_id_tipo_producto'),
        ('Servicios', '0003_alter_servicios_id_servicios'),
        ('Usuarios', '0004_usuarios_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_factura', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('placa', models.CharField(max_length=7)),
                ('documento_M', models.CharField(max_length=10)),
                ('id_metodo_pago', models.PositiveSmallIntegerField()),
                ('NIT', models.CharField(max_length=9)),
                ('Total', models.FloatField()),
                ('Subtotal', models.FloatField()),
                ('Iva', models.FloatField()),
                ('Descuento', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DetalleServicio',
            fields=[
                ('id_detalle_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.FloatField(blank=True, null=True)),
                ('documento', models.ForeignKey(limit_choices_to={'Rol': 1}, on_delete=django.db.models.deletion.CASCADE, to='Usuarios.usuarios')),
                ('id_servicios', models.ForeignKey(db_column='id_servicios', on_delete=django.db.models.deletion.CASCADE, to='Servicios.servicios')),
                ('id_factura', models.ForeignKey(db_column='id_factura', on_delete=django.db.models.deletion.CASCADE, to='Factura.factura')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleProducto',
            fields=[
                ('id_detalle_producto', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.FloatField(blank=True, null=True)),
                ('cantidad', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='Productos.productos')),
                ('id_factura', models.ForeignKey(db_column='id_factura', on_delete=django.db.models.deletion.CASCADE, to='Factura.factura')),
            ],
        ),
    ]
