# Generated by Django 5.0.6 on 2024-06-22 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Empresa', '0001_initial'),
        ('Productos', '0001_initial'),
        ('Servicios', '0001_initial'),
        ('Usuarios', '0001_initial'),
        ('Vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id_metodo_pago', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_factura', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('Total', models.FloatField()),
                ('Subtotal', models.FloatField()),
                ('Iva', models.FloatField()),
                ('Descuento', models.FloatField()),
                ('nit', models.ForeignKey(db_column='nit', on_delete=django.db.models.deletion.CASCADE, to='Empresa.empresa')),
                ('placa', models.ForeignKey(db_column='placa', on_delete=django.db.models.deletion.CASCADE, to='Vehiculo.vehiculo')),
                ('id_metodo_pago', models.ForeignKey(db_column='id_metodo_pago', on_delete=django.db.models.deletion.CASCADE, to='Factura.metodopago')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleServicio',
            fields=[
                ('id_detalle_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('documento_mecanico', models.ForeignKey(limit_choices_to={'Rol': 1}, on_delete=django.db.models.deletion.CASCADE, to='Usuarios.usuarios')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Servicios.servicios')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_servicio', to='Factura.factura')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleProducto',
            fields=[
                ('id_detalle_producto', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.FloatField(blank=True, null=True)),
                ('cantidad', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.productos')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_producto', to='Factura.factura')),
            ],
        ),
    ]
