# Generated by Django 5.0.6 on 2024-06-20 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Factura', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleservicio',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True),
        ),
    ]
