# Generated by Django 5.0.6 on 2024-06-15 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0002_alter_productos_id_tipo_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoproducto',
            name='id_tipo_producto',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
