# Generated by Django 5.0.6 on 2024-06-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('Documento', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(blank=True, max_length=25, null=True)),
                ('Apellido', models.CharField(blank=True, max_length=30, null=True)),
                ('Celular', models.CharField(blank=True, max_length=10, null=True)),
                ('F_Nacimiento', models.DateField(blank=True, null=True)),
                ('Correo', models.EmailField(blank=True, max_length=50, null=True)),
                ('Direccion', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
