# Generated by Django 5.0.6 on 2024-06-14 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_rename_mecanicos_usuarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
