# Generated by Django 5.0.6 on 2024-06-15 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0003_remove_usuarios_usuario_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='Rol',
            field=models.IntegerField(choices=[(1, 'Mecanico'), (2, 'Admin')], default=1),
        ),
    ]
