# Generated by Django 5.0.6 on 2024-06-17 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0004_usuarios_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='Rol',
            field=models.IntegerField(blank=True, choices=[(1, 'Mecánico'), (2, 'Administrador')], default=1, null=True),
        ),
    ]
